functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен иметь возможность регистрации пользователей.
  - Сайт должен состовлять и выводить рекомендуемые товары, с учетом уже просмотренных товаров.
  - Пользователь должен иметь возможность добавлять товары в избранные и просматривать их содержимое.
  - Пользователь должен иметь возможность сравнения товаров по их характеристикам.
  - Веб-сайт должен иметь современный дизайн
  - Пользователь должен иметь возможность просматривать сделанные заказы и отслеживать их исполнение.
  - Пользователь должен иметь возможность изменять количество товара, добавленного в корзину.
 
